### ISSUE TITLE
git clone failed

### ISSUE THREAD

**Issue by ahoehma** [aws/aws-k8s-tester#109]
$ git clone https://github.com/aws/aws-k8s-tester.git
Cloning into 'aws-k8s-tester'...
remote: Enumerating objects: 858, done.
remote: Counting objects: 100% (858/858), done.
remote: Compressing objects: 100% (520/520), done.
remote: Total 37086 (delta 421), reused 550 (delta 235), pack-reused 36228
Receiving objects: 100% (37086/37086), 34.73 MiB | 8.92 MiB/s, done.
Resolving deltas: 100% (20344/20344), done.
error: invalid path 'eks/cluster-loader/artifacts/MetricsForE2E_load_2020-06-18T22:18:53-07:00.json'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

$ git --version
git version 2.27.0.windows.1

**Comment by gyuho** [comment]
Is underscore valid character in windows?

**Comment by ahoehma** [comment]
Yes. I think so.

**Comment by gyuho** [comment]
Should be fixed via https://github.com/aws/aws-k8s-tester/commit/2f0566d170705faeb6b5780719b83f0520bccb72.
