### ISSUE TITLE
Fixture names with colons make import of this project impossible

### ISSUE THREAD

**Issue by alvaroaleman** [aws/aws-k8s-tester#129]
For example:
```
github.com/aws/aws-k8s-tester/eks: create zip: malformed file path "eks/cluster-loader/artifacts/MetricsForE2E_load_2020-06-18T22:18:53-07:00.json": invalid char ':'
```

Go seems to be creating a zip archive which doesn't import those characters which in turn leads to the non-importability. Worse, fetching it with the proxy results in a 410 which _I believe_ is originally caused by the inability to create a zip archive.

**Comment by gyuho** [comment]
Similar https://github.com/aws/aws-k8s-tester/issues/109.

Will fix it shortly. Thanks for the report!

**Comment by gyuho** [comment]
Should be fixed via https://github.com/aws/aws-k8s-tester/commit/2f0566d170705faeb6b5780719b83f0520bccb72.
