### ISSUE TITLE
Grafana add-on is failing

### ISSUE THREAD

**Issue by gyuho** [aws/aws-k8s-tester#131]
```
$ /tmp/kubectl-test-v1.17.6 --kubeconfig=/tmp/eks-2020071709-mountain862z.kubeconfig.yaml -n grafana logs pod/grafana-6867666fbc-76tsk -c init-chown-data

standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by gyuho** [comment]
ref. https://github.com/helm/charts/commit/dbecf6b10c7ba56ed5b2c391b9684137829e585b#diff-2ddabd2bb7172882a1587422791af850

**Comment by gyuho** [comment]
ref. https://github.com/helm/charts/pull/23195

**Comment by GMartinez-Sisti** [comment]
@gyuho this probably fixed it https://github.com/helm/charts/pull/23240

**Comment by gyuho** [comment]
@GMartinez-Sisti Thanks. Will test it out!

**Comment by gyuho** [comment]
@GMartinez-Sisti Fixed. Thanks!

> {"level":"info","ts":"2020-07-17T12:43:01.208-0700","caller":"helm/helm.go:250","msg":"loaded chart via remote repo","namespace":"grafana","chart-repo":"https://kubernetes-charts.storage.googleapis.com","release-name":"grafana","chart-path":"/home/ANT.AMAZON.COM/leegyuho/.cache/helm/repository/grafana-5.4.1.tgz","chart-full-path":"grafana","chart-name":"grafana","chart-app-version":"7.0.5"}
