### ISSUE TITLE
Use Amazon Linux 2 for kubeadm tests

### ISSUE THREAD

**Issue by gyuho** [aws/aws-k8s-tester#39]
Currently, kubeadm (v1.13.2) does not work on Amazon Linux 2.

```
[patchnode] Uploading the CRI Socket information "/var/run/dockershim.sock" to the Node API object "ip-192-168-222-150.us-west-2.compute.internal" as an annotation
[kubelet-check] Initial timeout of 40s passed.
error execution phase upload-config/kubelet: Error writing Crisocket information for the control-plane node: timed out waiting for the condition
```

- https://github.com/kubernetes/kubeadm/issues/1092
- https://github.com/kubernetes/kubeadm/issues/1218

**Comment by gyuho** [comment]
@leakingtapan 

We will use the Ubuntu as a base image, for now.

**Comment by gyuho** [comment]
@leakingtapan

Actually, I will try Amazon Linux 2, one more time.

**Comment by siulcode** [comment]
@gyuho We are getting the same issue trying to setup a Kube cluster with Aws Linux 2 

`error execution phase upload-config/kubelet: Error writing Crisocket information for the control-plane node: timed out waiting for the condition
`

Could this be due to a decrease on that timeout?

**Comment by gyuho** [comment]
@siulcode Thanks for the report. I haven't had much time on this, but planned to debug more soon. If you can provide a way to reproduce, it would be helpful!

**Comment by gyuho** [comment]
Got the basic master and worker nodes working. Will release a new binary.
