### ISSUE TITLE
Can not create cluster just with AWS Credential Env

### ISSUE THREAD

**Issue by Jeffwan** [aws/aws-k8s-tester#42]
I meet an issue that if I don't have ~/.aws/credential but using `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` instead. I can not create cluster and it fails in config.ValidateAndSetDefaults(). 
https://github.com/aws/aws-k8s-tester/blob/ee248f9e8d69961656de1092a816e719e8566f27/eksconfig/config.go#L779-L781

```
aws-k8s-tester eks create cluster --path ./aws-k8s-tester-eks.yaml
failed to validate configuration "./aws-k8s-tester-eks.yaml" (AWSCredentialToMountPath "/Users/myname/.aws/credentials" does not exist)
```

Credential file and env are all native experiences we need to support. The use case is I mount aws secret on the pod which is used to create cluster. 

Very low priority, I can help add this support later.

**Comment by gyuho** [comment]
Thanks for the report. Will push a quick fix!

**Comment by gyuho** [comment]
We instead improved the error message to instruct the users to write their own credential file, to simplify the credential file handling, and also prevent accidental credential key leaks (e.g. user may forget to delete the file, if we automatically write credential files based on envs).
