### ISSUE TITLE
Bump OpenCensus version or delete it

### ISSUE THREAD

**Issue by randomvariable** [aws/aws-k8s-tester#57]
https://github.com/aws/aws-k8s-tester/blob/master/go.mod#L5 pulls in a now non-existent version of Apache Thrift.

Recommend it is bumped (as a newer release references to new Github repo for Apache Thrift), or deleted, as it's not clear where it's being used.

Affects https://github.com/kubernetes/test-infra/pull/14172

**Comment by gyuho** [comment]
Fixed. Thanks.

**Comment by techtonik** [comment]
@randomvariable did you mean https://github.com/aws/aws-k8s-tester/blob/3f6e1569a6d17e3c7b1042cb0c7eb3a25b9f8ed7/go.mod#L5 fixed by 2d71abc6ce2e32ebd66fbaaf356eec4c133c113e? Where does it pull Thrift?
