### ISSUE TITLE
can't load package: package github.com/aws/aws-k8s-tester/ekstester

### ISSUE THREAD

**Issue by andysmagana** [aws/aws-k8s-tester#73]
Running Ubuntu 18.04.3 LTS

Trying to install kubetest on ubuntu master node in kubernetes cluster I get this 

`go get -u k8s.io/test-infra/kubetest
package github.com/aws/aws-k8s-tester/ekstester: cannot find package "github.com/aws/aws-k8s-tester/ekstester" in any of:
	/usr/lib/go-1.13/src/github.com/aws/aws-k8s-tester/ekstester (from $GOROOT)
	/home/vagrant/go/src/github.com/aws/aws-k8s-tester/ekstester (from $GOPATH)
`

**Comment by casibbald** [comment]
Any update on this?

**Comment by brianpursley** [comment]
I ran into the same problem and did a little digging.

It looks like ekstester was removed from aws-k8s-tester starting in [version 0.5.0](https://github.com/aws/aws-k8s-tester/commit/2e28fc402e559d4deccd08c072e5a97931e80929) to support kubetest2.

However, in test-infra, kubetest and kubetest2 live in the same repo and share the same go.mod, and the shared go.mod is telling it to use aws-k8s-tester:0.5.4.  So that is causing kubetest to fail because 0.5.4 doesn't contain ekstester anymore.

**Comment by andysmagana** [comment]
Wow that’s amazing digging what to you indicated that?  since I am learning k8s and studying for the CKA cert it would be helpful how you picked up on the difference of versions.

**Comment by andysmagana** [comment]
Wow that’s amazing digging what to you indicated that? since I am learning k8s and studying for the CKA cert it would be helpful how you picked up on the difference of versions.

**Comment by brianpursley** [comment]
I went back through the commit history in github until I found where the ekstester directory was removed.  I'm still not quite sure how to fix the problem though...

**Comment by gyuho** [comment]
@andysmagana @brianpursley Seems like go mod does not work as expected. It's vendored in test-infra with semantic versioning.

Let me add it back to see if it works.

**Comment by gyuho** [comment]
Can you try again?

**Comment by brianpursley** [comment]
Thanks @gyuho 

I tried it again and now I'm getting a different error:
```
$ go get -u k8s.io/test-infra/kubetest
# k8s.io/client-go/transport
go/src/k8s.io/client-go/transport/round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool
go/src/k8s.io/client-go/transport/round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool
go/src/k8s.io/client-go/transport/round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool
go/src/k8s.io/client-go/transport/round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool
```
but that doesn't seem to be related to aws-k8s-tester so that is probably a problem in test-infra.

**Comment by gyuho** [comment]
@brianpursley Yeah, seems like go mod issue. Can we create an issue in `test-infra`?
