### ISSUE TITLE
Log polling wait times 

### ISSUE THREAD

**Issue by mogren** [aws/aws-k8s-tester#75]
When running, the tests do a lot of polling waiting for state changes. It would be really neat to save the times each event took and print as a final log. Later on, we could use the times to delay the first poll until the estimated completion. For some events, this might vary too much, or they are too quick to matter, but for some multi minute actions, like creating or deleting an EKS cluster, we should be able to get some interesting metrics.

**Comment by gyuho** [comment]
Done via https://github.com/aws/aws-k8s-tester/pull/74.

Added the following fields for each step:

```go
// CreateTook is the duration that took to create the resource.
CreateTook time.Duration `json:"create-took" read-only:"true"`
// CreateTookString is the duration that took to create the resource.
CreateTookString string `json:"create-took-string" read-only:"true"`
// DeleteTook is the duration that took to create the resource.
DeleteTook time.Duration `json:"delete-took" read-only:"true"`
// DeleteTookString is the duration that took to create the resource.
DeleteTookString string `json:"delete-took-string" read-only:"true"`
```

Thanks for the suggestion!

**Comment by jaypipes** [comment]
@gyuho #74 is for moving managed node group functionality out into a separate package. Are you saying you introduced the timing functionality in the same patch that moves MNG into a separate package?

**Comment by gyuho** [comment]
@jaypipes Yeah, I included in the same commit https://github.com/aws/aws-k8s-tester/commit/edb463593e92ee6f0b40fa253c64e4cd39294937#diff-aede2c5936b21075dd4ca5008a82a4e5R237-R244
