### ISSUE TITLE
Document config settings and have examples for how to run 

### ISSUE THREAD

**Issue by mogren** [aws/aws-k8s-tester#76]
I'd like to know how to configure the setup and what variables are available

- [ ] Document all variables
- [ ] Example with EKS setup
- [ ] Example with Kops

**Comment by gyuho** [comment]
Documented https://github.com/aws/aws-k8s-tester#aws-k8s-tester-ec2 and https://github.com/aws/aws-k8s-tester#aws-k8s-tester-eks.

**Comment by gyuho** [comment]
Added https://github.com/aws/aws-k8s-tester/blob/master/ec2config/README.md and https://github.com/aws/aws-k8s-tester/blob/master/eksconfig/README.md.
