### ISSUE TITLE
how to dump cluster logs now?

### ISSUE THREAD

**Issue by cofyc** [aws/aws-k8s-tester#77]
hi, @gyuho 

https://github.com/kubernetes/test-infra/blob/92e4176fa4877ba1823eabfc576fe1665f8f3762/kubetest/eks.go#L237-L259

it seems that `test get-worker-node-logs` and `test dump-cluster-logs` does not exist anymore. How can I dump cluster logs now?

**Comment by gyuho** [comment]
It's replaced by https://github.com/aws/aws-k8s-tester/blob/master/eks/mng/logs.go#L32.
If you create a managed node group, it will automatically fetch logs.

**Comment by cofyc** [comment]
Thanks!
