### ISSUE TITLE
Deletion of resources should be graceful 

### ISSUE THREAD

**Issue by SaranBalaji90** [aws/aws-k8s-tester#79]
If deletion of namespace fails because of resource not found, https://github.com/aws/aws-k8s-tester/blame/7708d34f8a152b8878746dabb2c355cc576a2e10/eks/namespace.go#L40 then we throw 4xx. We should instead handle it similar to https://github.com/aws/aws-k8s-tester/blob/7708d34f8a152b8878746dabb2c355cc576a2e10/e2e/framework/resource/namespace.go#L86 

Test run in CNI repo where test failed
https://app.circleci.com/jobs/github/aws/amazon-vpc-cni-k8s/185

```
aws-k8s-tester EKS deleteNamespace ("/tmp/cni-test/cluster-cni-test-24392/cni-test-24392.yaml", 'kubectl --kubeconfig=/tmp/cni-test/cluster-cni-test-24392/kubeconfig --namespace=cni-test-24392')
{"level":"info","ts":"2020-02-27T08:00:27.389Z","caller":"eks/namespace.go:40","msg":"deleting namespace","namespace":"cni-test-24392"}
{"level":"warn","ts":"2020-02-27T08:00:28.105Z","caller":"eks/eks.go:787","msg":"failed to delete namespace","namespace":"cni-test-24392","error":"namespaces \"cni-test-24392\" not found"}

```

**Comment by gyuho** [comment]
Fixed via https://github.com/aws/aws-k8s-tester/blob/master/CHANGELOG-0.6.md#v063-2020-02-28.
